---
- name: Ensure unzip is installed
  ansible.builtin.package:
    name: unzip
    state: present
    update_cache: true

- name: Check if aws cli is installed
  ansible.builtin.command: /usr/local/bin/aws --version
  register: _awscli_version
  changed_when: false
  failed_when: false

- name: Download and install aws cli v2
  when: _awscli_version.rc != 0 or awscli_package_state == 'latest'
  block:
    - name: Determine architecture
      ansible.builtin.set_fact:
        _awscli_arch: "{{ 'aarch64' if ansible_facts['architecture'] == 'aarch64' else 'x86_64' }}"

    - name: Download aws cli v2
      ansible.builtin.unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ _awscli_arch }}.zip"
        dest: /tmp
        remote_src: true

    - name: Install aws cli v2
      ansible.builtin.command: /tmp/aws/install --update
      changed_when: true

    - name: Remove installer files
      ansible.builtin.file:
        path: /tmp/aws
        state: absent

- name: Ensure ~/.aws directory exists
  ansible.builtin.file:
    group: "{{ item.group }}"
    mode: "0755"
    owner: "{{ item.name }}"
    path: "{{ item.home }}/.aws"
    state: directory
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure ~/.aws/config file exists
  ansible.builtin.template:
    dest: "{{ item.home }}/.aws/config"
    group: "{{ item.group }}"
    mode: "0644"
    owner: "{{ item.name }}"
    src: config.j2
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure ~/.aws/credentials file exists
  ansible.builtin.template:
    dest: "{{ item.home }}/.aws/credentials"
    group: "{{ item.group }}"
    mode: "0600"
    owner: "{{ item.name }}"
    src: credentials.j2
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true
