---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ansible-role-awscli-debian-9
    image: debian:9
  - name: ansible-role-awscli-debian-10
    image: debian:10
  - name: ansible-role-awscli-ubuntu-1604
    image: ubuntu:16.04
  - name: ansible-role-awscli-ubuntu-1804
    image: ubuntu:18.04

lint:
  name: yamllint

provisioner:
  name: ansible
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
