---
dependency:
  name: galaxy
  enabled: False

driver:
  name: docker

platforms:
  - name: ansible-role-awscli-debian-10
    image: debian:10
  - name: ansible-role-awscli-debian-11
    image: debian:11
  - name: ansible-role-awscli-ubuntu-1804
    image: ubuntu:18.04
  - name: ansible-role-awscli-ubuntu-2004
    image: ubuntu:20.04

lint: |
    yamllint .
    ansible-lint
    flake8

provisioner:
  name: ansible

verifier:
  name: testinfra
